# Generated by Django 6.0.6 on 2026-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_journalcategory_journaltag_newsletter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='uncategorized', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='journal',
            name='meta_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reading_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='journalimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
