# Generated by Django 6.0.6 on 2026-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_alter_award_link_alter_journal_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='awards',
            field=models.TextField(blank=True, help_text='Awards and recognitions (comma or newline separated)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/profiles/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('principal', 'Principal Architect'), ('senior', 'Senior Architect'), ('associate', 'Associate Architect'), ('designer', 'Designer'), ('lead', 'Project Lead'), ('intern', 'Intern'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
