# Generated by Django 6.0.6 on 2026-06-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_founder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founder',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='founder',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founder',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='founder',
            name='photo_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='founder',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('principal', 'Principal Architect'), ('director', 'Director')], default='founder', max_length=50),
        ),
        migrations.CreateModel(
            name='FounderAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('is_experience', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='myapp.founder')),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
    ]
