# Generated by Django 6.0.6 on 2026-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_founder_options_founder_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default-avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
